steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sharkops-239501/shark-ops-ui-image:v1', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sharkops-239501/shark-ops-ui-image:v1']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'create', 'shark-ops-cluster', '--num-nodes=2', '--zone=us-east4-b']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['run', 'shark-ops-ui-deployment', '--image=gcr.io/sharkops-239501/shark-ops-ui-image:v1', '--port=8080']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=shark-ops-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['expose', 'deployment', 'shark-ops-ui-deployment', '--type=LoadBalancer', '--port=80', '--target-port=8080']

timeout: 660s
tags: ['mytag1', 'mytag2']
images: ['gcr.io/sharkops-239501/shark-ops-ui-image:v1']