apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sssuthe-com-tls
spec:
  secretName: sssuthe-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sssuthe.com
  dnsNames:
    - sssuthe.com
    - www.sssuthe.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sssuthe.com
          - www.sssuthe.com